version: "3.8"

services:
  mysql:
    image: mysql:8.4
    container_name: webcrawler-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: webcrawler
      MYSQL_USER: crawleruser
      MYSQL_PASSWORD: crawlerpass
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: webcrawler-adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  db_data:
